body:
  - type: input
    id: name
    attributes:
      label: 이름 Your Name
      description: "한국인은 한국어로 써주세요. Provide your Korean name as well if you are a Korean."
    validations:
      required: true
  - type: input
    id: artifact
    attributes:
      label: 작업물 Your work
      description: "작업물의 링크. Link to your contribution."
    validations:
      required: true
  - type: textarea
    id: long
    attributes:
      label: Detailed Description
      description: "작업의 상세 설명. 한국인은 한국어로 쓰고 영문 번역을 첨부해주세요. Detailed description"
      value: |
        ...
    validations:
      required: true
